### ISSUE TITLE
Script Annotation Example is breaking with TypeError

### ISSUE THREAD

**Issue by vikramsg** [argoproj-labs/hera#804]
<h2>Pre-bug-report checklist</h2>

**1. This bug can be reproduced using YAML**
- [ ] Yes [👉 Please report a bug to the Argo Workflows GitHub 👈](https://github.com/argoproj/argo-workflows/issues/new/choose)
- [x] No

**2. This bug occurs when...**
- [ ] running Hera code without submitting to Argo (e.g. when exporting to YAML)
- [x] running Hera code and submitting to Argo

<h2>Bug report</h2>

I wanted to try out running scripts with Annotated inputs and outputs, so I decided to use the script annotation example. However, it breaks with the following error. 

_Error log if applicable_:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/mocca/.local/lib/python3.8/site-packages/hera/workflows/runner.py", line 276, in <module>
    _run()
  File "/home/mocca/.local/lib/python3.8/site-packages/hera/workflows/runner.py", line 269, in _run
    result = _runner(args.entrypoint, kwargs_list)
  File "/home/mocca/.local/lib/python3.8/site-packages/hera/workflows/runner.py", line 244, in _runner
    _save_annotated_return_outputs(function(**kwargs), output_annotations)
  File "/home/mocca/.local/lib/python3.8/site-packages/hera/workflows/runner.py", line 174, in _save_annotated_return_outputs
    if not isinstance(res, dest[0]):
  File "/usr/lib/python3.8/typing.py", line 769, in __instancecheck__
    return self.__subclasscheck__(type(obj))
  File "/usr/lib/python3.8/typing.py", line 777, in __subclasscheck__
    raise TypeError("Subscripted generics cannot be used with"
TypeError: Subscripted generics cannot be used with class and instance checks
```

**To Reproduce**
Full Hera code to reproduce the bug:

It is the following, only with added configuration for Argo. 
https://github.com/argoproj-labs/hera/blob/main/examples/workflows/script_annotations_inputs.py

**Expected behavior**
Workflow should run. 

**Environment**
 - OS: [Kubuntu]
 - Browser: [firefox]
 - Version of Hera: [5.7.1, 5.7.3 as well as main]
 - Version of Argo: [3.4.4]

**Comment by elliotgunton** [comment]
This was fixed in #791. We can look to make a release 🚀

**Comment by vikramsg** [comment]
That is strange since I tried using `main` directly and it was still an issue.

**Comment by elliotgunton** [comment]
@vikramsg if you could double check that the `main` branch of hera is being used it would be appreciated 🙏 

From the error log
```
  File "/home/mocca/.local/lib/python3.8/site-packages/hera/workflows/runner.py", line 244, in _runner
    _save_annotated_return_outputs(function(**kwargs), output_annotations)
```
The `_save_annotated_return_outputs` call is on line 253 on `main`, so I am suspecting `python3.8/site-packages/hera` is not actually from `main`

**Comment by vikramsg** [comment]
Yeah, sorry. I updated it locally but not in the Docker image. This process of updating Docker images before submitting a job every time is very un-intuitive.

**Comment by elliotgunton** [comment]
Yes, we had this discussion https://github.com/argoproj-labs/hera/discussions/665 around that problem
